version: "3.3"

services:
    db-dev:
        image: mariadb:11.2.2-jammy
        restart: always
        environment:
            MARIADB_DATABASE: ${DB_DATABASE}
            MARIADB_USER: ${DB_USER}
            MARIADB_PASSWORD: ${DB_PASSWORD}
            MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
        networks:
            - default
        ports:
            - "3307:3306"
        volumes:
            - ./db:/var/lib/mysql
        healthcheck:
            test:
                [
                    "CMD",
                    "healthcheck.sh",
                    "--su-mysql",
                    "--connect",
                    "--innodb_initialized",
                ]
            interval: 1s
            timeout: 20s
            retries: 30

    api-dev:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "81:3000"
        volumes:
            - .:/app
        environment:
            NODE_ENV: development
            PORT: 3000
            DB_HOST: "db-dev"
            DB_DATABASE: ${DB_DATABASE}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
        networks:
            - default
        depends_on:
            db-dev:
                condition: service_healthy
