- name: Update web servers
  hosts: webservers
  remote_user: admin
  become: true
  become_method: sudo

  tasks:
      - name: Install Docker
        apt:
            name: docker.io
            state: present
            update_cache: yes
