name: CI

run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.sha }}

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    upload-artifact:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
              with:
                  images: skelletondude/pipeline-cesi

            - name: Build and push Docker image
              uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

    # test:
    #     needs: [install]
    #     runs-on: ubuntu-latest
    #     strategy:
    #         matrix:
    #             browser: [chrome, edge]
    #     steps:
    #         - uses: actions/checkout@v2
    #         - uses: actions/cache/restore@v3
    #           with:
    #               path: |
    #                   ~/.cache/Cypress
    #                   node_modules
    #               key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    #         - uses: actions/cache/restore@v3
    #           with:
    #               path: |
    #                   ~/.npm
    #                   ${{ github.workspace }}/.next
    #               key: ${{ runner.os }}-node-${{ github.sha }}
    #         - name: Cypress run
    #           uses: cypress-io/github-action@v6
    #           with:
    #               config-file: cypress.config.ts
    #               start: npm run start
    #               install: false
    #               browser: ${{ matrix.browser }}
    #         - name: Upload Cypress videos
    #           uses: actions/upload-artifact@v4
    #           with:
    #               name: cypress-videos-${{ matrix.browser }}
    #               path: cypress/videos

    # deploy:
    #     needs: [install]
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: webfactory/ssh-agent@v0.8.0
    #           with:
    #               ssh-private-key: ${{ secrets.SSH_KEY }}
    #         - run: |
    #               ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
    #               cd ~/intro-to-ci-cd-celian-hamon && \
    #               git pull && \
    #               sudo docker compose down && \
    #               sudo docker compose up -d --build"
